export interface JobSite {
  id: string
  name: string
  url: string
  logo_url: string
  description: string
  countries: string[]
  category: 'general' | 'tech' | 'remote' | 'freelance' | 'executive' | 'regional'
}

export const CATEGORIES = [
  { value: 'all', label: 'All' },
  { value: 'general', label: 'General' },
  { value: 'tech', label: 'Tech' },
  { value: 'remote', label: 'Remote' },
  { value: 'freelance', label: 'Freelance' },
  { value: 'executive', label: 'Executive' },
  { value: 'regional', label: 'Regional' },
] as const

function favicon(domain: string) {
  return `https://www.google.com/s2/favicons?domain=${domain}&sz=64`
}

export const JOB_SITES: JobSite[] = [
  // ── General ──────────────────────────────────────────
  {
    id: 'indeed',
    name: 'Indeed',
    url: 'https://www.indeed.com',
    logo_url: favicon('indeed.com'),
    description: 'World\'s largest job board with millions of listings',
    countries: ['GLOBAL'],
    category: 'general',
  },
  {
    id: 'linkedin',
    name: 'LinkedIn Jobs',
    url: 'https://www.linkedin.com/jobs',
    logo_url: favicon('linkedin.com'),
    description: 'Professional network with job listings and referrals',
    countries: ['GLOBAL'],
    category: 'general',
  },
  {
    id: 'glassdoor',
    name: 'Glassdoor',
    url: 'https://www.glassdoor.com',
    logo_url: favicon('glassdoor.com'),
    description: 'Job search with company reviews and salary data',
    countries: ['GLOBAL'],
    category: 'general',
  },
  {
    id: 'monster',
    name: 'Monster',
    url: 'https://www.monster.com',
    logo_url: favicon('monster.com'),
    description: 'Veteran job board with resume tools and career advice',
    countries: ['GLOBAL'],
    category: 'general',
  },
  {
    id: 'careerbuilder',
    name: 'CareerBuilder',
    url: 'https://www.careerbuilder.com',
    logo_url: favicon('careerbuilder.com'),
    description: 'Job search with AI-powered recommendations',
    countries: ['US', 'GB', 'CA'],
    category: 'general',
  },
  {
    id: 'ziprecruiter',
    name: 'ZipRecruiter',
    url: 'https://www.ziprecruiter.com',
    logo_url: favicon('ziprecruiter.com'),
    description: 'One-click apply and smart job matching',
    countries: ['US', 'GB', 'CA'],
    category: 'general',
  },
  {
    id: 'simplyhired',
    name: 'SimplyHired',
    url: 'https://www.simplyhired.com',
    logo_url: favicon('simplyhired.com'),
    description: 'Aggregated listings with salary estimator',
    countries: ['GLOBAL'],
    category: 'general',
  },
  {
    id: 'jobrapido',
    name: 'Jobrapido',
    url: 'https://www.jobrapido.com',
    logo_url: favicon('jobrapido.com'),
    description: 'International job search engine across 58 countries',
    countries: ['GLOBAL'],
    category: 'general',
  },
  {
    id: 'jooble',
    name: 'Jooble',
    url: 'https://jooble.org',
    logo_url: favicon('jooble.org'),
    description: 'Search engine aggregating jobs from thousands of sites',
    countries: ['GLOBAL'],
    category: 'general',
  },
  {
    id: 'google-jobs',
    name: 'Google Jobs',
    url: 'https://www.google.com/search?q=jobs+near+me&ibp=htl;jobs',
    logo_url: favicon('google.com'),
    description: 'Google Search integrated job listings',
    countries: ['GLOBAL'],
    category: 'general',
  },

  // ── Tech ─────────────────────────────────────────────
  {
    id: 'stackoverflow',
    name: 'Stack Overflow Jobs',
    url: 'https://stackoverflow.com/jobs',
    logo_url: favicon('stackoverflow.com'),
    description: 'Developer-focused jobs from the coding community',
    countries: ['GLOBAL'],
    category: 'tech',
  },
  {
    id: 'wellfound',
    name: 'Wellfound',
    url: 'https://wellfound.com',
    logo_url: favicon('wellfound.com'),
    description: 'Startup jobs (formerly AngelList Talent)',
    countries: ['GLOBAL'],
    category: 'tech',
  },
  {
    id: 'dice',
    name: 'Dice',
    url: 'https://www.dice.com',
    logo_url: favicon('dice.com'),
    description: 'Tech-specific job board for IT professionals',
    countries: ['US'],
    category: 'tech',
  },
  {
    id: 'hackerrank',
    name: 'HackerRank',
    url: 'https://www.hackerrank.com/jobs',
    logo_url: favicon('hackerrank.com'),
    description: 'Jobs matched by coding skill assessments',
    countries: ['GLOBAL'],
    category: 'tech',
  },
  {
    id: 'hired',
    name: 'Hired',
    url: 'https://hired.com',
    logo_url: favicon('hired.com'),
    description: 'Companies apply to you with salary upfront',
    countries: ['US', 'GB', 'CA'],
    category: 'tech',
  },
  {
    id: 'techcareers',
    name: 'TechCareers',
    url: 'https://www.techcareers.com',
    logo_url: favicon('techcareers.com'),
    description: 'IT and engineering career opportunities',
    countries: ['US'],
    category: 'tech',
  },
  {
    id: 'yc-wats',
    name: 'Work at a Startup',
    url: 'https://www.workatastartup.com',
    logo_url: favicon('workatastartup.com'),
    description: 'Y Combinator portfolio company jobs',
    countries: ['GLOBAL'],
    category: 'tech',
  },
  {
    id: 'github-jobs',
    name: 'GitHub Jobs',
    url: 'https://github.com/about/careers',
    logo_url: favicon('github.com'),
    description: 'Opportunities at GitHub and open source community',
    countries: ['GLOBAL'],
    category: 'tech',
  },

  // ── Remote ───────────────────────────────────────────
  {
    id: 'weworkremotely',
    name: 'We Work Remotely',
    url: 'https://weworkremotely.com',
    logo_url: favicon('weworkremotely.com'),
    description: 'Largest remote work community with curated listings',
    countries: ['GLOBAL'],
    category: 'remote',
  },
  {
    id: 'remoteco',
    name: 'Remote.co',
    url: 'https://remote.co',
    logo_url: favicon('remote.co'),
    description: 'Hand-screened remote jobs and company profiles',
    countries: ['GLOBAL'],
    category: 'remote',
  },
  {
    id: 'flexjobs',
    name: 'FlexJobs',
    url: 'https://www.flexjobs.com',
    logo_url: favicon('flexjobs.com'),
    description: 'Vetted remote and flexible job opportunities',
    countries: ['GLOBAL'],
    category: 'remote',
  },
  {
    id: 'remotive',
    name: 'Remotive',
    url: 'https://remotive.com',
    logo_url: favicon('remotive.com'),
    description: 'Remote tech jobs updated daily',
    countries: ['GLOBAL'],
    category: 'remote',
  },
  {
    id: 'workingnomads',
    name: 'Working Nomads',
    url: 'https://www.workingnomads.com',
    logo_url: favicon('workingnomads.com'),
    description: 'Curated remote jobs for digital nomads',
    countries: ['GLOBAL'],
    category: 'remote',
  },

  // ── Freelance ────────────────────────────────────────
  {
    id: 'upwork',
    name: 'Upwork',
    url: 'https://www.upwork.com',
    logo_url: favicon('upwork.com'),
    description: 'Freelance marketplace for any skill set',
    countries: ['GLOBAL'],
    category: 'freelance',
  },
  {
    id: 'fiverr',
    name: 'Fiverr',
    url: 'https://www.fiverr.com',
    logo_url: favicon('fiverr.com'),
    description: 'Gig-based freelance services marketplace',
    countries: ['GLOBAL'],
    category: 'freelance',
  },
  {
    id: 'toptal',
    name: 'Toptal',
    url: 'https://www.toptal.com',
    logo_url: favicon('toptal.com'),
    description: 'Elite freelance talent for top companies',
    countries: ['GLOBAL'],
    category: 'freelance',
  },
  {
    id: 'freelancer',
    name: 'Freelancer',
    url: 'https://www.freelancer.com',
    logo_url: favicon('freelancer.com'),
    description: 'Bid on projects across thousands of categories',
    countries: ['GLOBAL'],
    category: 'freelance',
  },

  // ── Executive ────────────────────────────────────────
  {
    id: 'theladders',
    name: 'TheLadders',
    url: 'https://www.theladders.com',
    logo_url: favicon('theladders.com'),
    description: 'High-paying jobs for experienced professionals',
    countries: ['US'],
    category: 'executive',
  },
  {
    id: 'efinancialcareers',
    name: 'eFinancialCareers',
    url: 'https://www.efinancialcareers.com',
    logo_url: favicon('efinancialcareers.com'),
    description: 'Finance and banking career opportunities',
    countries: ['GLOBAL'],
    category: 'executive',
  },
  {
    id: 'ladders',
    name: 'Ladders',
    url: 'https://www.theladders.com/jobs',
    logo_url: favicon('theladders.com'),
    description: '$100K+ jobs for senior-level professionals',
    countries: ['US'],
    category: 'executive',
  },

  // ── Regional ─────────────────────────────────────────
  {
    id: 'reed',
    name: 'Reed',
    url: 'https://www.reed.co.uk',
    logo_url: favicon('reed.co.uk'),
    description: 'UK\'s leading job site with 250,000+ listings',
    countries: ['GB'],
    category: 'regional',
  },
  {
    id: 'totaljobs',
    name: 'Totaljobs',
    url: 'https://www.totaljobs.com',
    logo_url: favicon('totaljobs.com'),
    description: 'UK job board covering all industries',
    countries: ['GB'],
    category: 'regional',
  },
  {
    id: 'seek',
    name: 'SEEK',
    url: 'https://www.seek.com.au',
    logo_url: favicon('seek.com.au'),
    description: 'Australia & New Zealand\'s top employment site',
    countries: ['AU', 'NZ'],
    category: 'regional',
  },
  {
    id: 'naukri',
    name: 'Naukri',
    url: 'https://www.naukri.com',
    logo_url: favicon('naukri.com'),
    description: 'India\'s largest job portal with millions of listings',
    countries: ['IN'],
    category: 'regional',
  },
  {
    id: 'stepstone',
    name: 'StepStone',
    url: 'https://www.stepstone.de',
    logo_url: favicon('stepstone.de'),
    description: 'Leading job board in Germany, Austria & Switzerland',
    countries: ['DE', 'AT', 'CH'],
    category: 'regional',
  },
  {
    id: 'pole-emploi',
    name: 'France Travail',
    url: 'https://www.francetravail.fr',
    logo_url: favicon('francetravail.fr'),
    description: 'France\'s national employment agency job listings',
    countries: ['FR'],
    category: 'regional',
  },
  {
    id: 'infojobs',
    name: 'InfoJobs',
    url: 'https://www.infojobs.net',
    logo_url: favicon('infojobs.net'),
    description: 'Top job portal in Spain and Italy',
    countries: ['ES', 'IT'],
    category: 'regional',
  },
  {
    id: 'pracuj',
    name: 'Pracuj.pl',
    url: 'https://www.pracuj.pl',
    logo_url: favicon('pracuj.pl'),
    description: 'Poland\'s leading job board and career platform',
    countries: ['PL'],
    category: 'regional',
  },
  {
    id: 'jobstreet',
    name: 'JobStreet',
    url: 'https://www.jobstreet.com.sg',
    logo_url: favicon('jobstreet.com.sg'),
    description: 'Southeast Asia\'s top recruitment platform',
    countries: ['SG'],
    category: 'regional',
  },
  {
    id: 'careers24',
    name: 'Careers24',
    url: 'https://www.careers24.com',
    logo_url: favicon('careers24.com'),
    description: 'South Africa\'s premier job search platform',
    countries: ['ZA'],
    category: 'regional',
  },
]
