import type { TemplateConfig } from './types'

export const executiveConfig: TemplateConfig = {
  id: 'executive',
  name: 'Executive',
  description: 'Serif, gold/navy, single-column, centered header',
  layout: 'single-column',
  premium: true,
  colors: {
    primary: '#1B2A4A',
    primaryLight: '#C9A84C',
    headerBg: '#1B2A4A',
    headerText: '#FFFFFF',
    sidebarBg: '#FFFFFF',
    sidebarText: '#333333',
    sidebarAccent: '#C9A84C',
    bodyText: '#333333',
    bodySecondary: '#666666',
    sectionTitle: '#1B2A4A',
    divider: '#C9A84C',
  },
  fonts: {
    heading: 'Times-Roman',
    headingBold: 'Times-Bold',
    body: 'Times-Roman',
    bodyBold: 'Times-Bold',
  },
  spacing: { pagePadding: 32, sectionGap: 14, itemGap: 8, sidebarWidth: '100%' },
  style: {
    headerCentered: true,
    sectionTitleUppercase: true,
    sectionTitleBorder: true,
    bulletChar: '\u2022',
    nameSize: 24,
    titleSize: 12,
    sectionTitleSize: 11,
    bodySize: 10,
    smallSize: 8,
  },
}

export const creativeConfig: TemplateConfig = {
  id: 'creative',
  name: 'Creative',
  description: 'Teal/coral, two-column right sidebar, bold',
  layout: 'two-column-right',
  premium: true,
  colors: {
    primary: '#0D9488',
    primaryLight: '#5EEAD4',
    headerBg: '#FFFFFF',
    headerText: '#0D9488',
    sidebarBg: '#0D9488',
    sidebarText: '#FFFFFF',
    sidebarAccent: '#F97316',
    bodyText: '#1F2937',
    bodySecondary: '#6B7280',
    sectionTitle: '#0D9488',
    divider: '#5EEAD4',
  },
  fonts: {
    heading: 'Helvetica',
    headingBold: 'Helvetica-Bold',
    body: 'Helvetica',
    bodyBold: 'Helvetica-Bold',
  },
  spacing: { pagePadding: 24, sectionGap: 14, itemGap: 8, sidebarWidth: '32%' },
  style: {
    headerCentered: false,
    sectionTitleUppercase: false,
    sectionTitleBorder: false,
    bulletChar: '\u25B8',
    nameSize: 22,
    titleSize: 11,
    sectionTitleSize: 11,
    bodySize: 9,
    smallSize: 8,
  },
}

export const techConfig: TemplateConfig = {
  id: 'tech',
  name: 'Tech',
  description: 'Dark header bar, monospace accents, grid layout',
  layout: 'single-column',
  premium: true,
  colors: {
    primary: '#111827',
    primaryLight: '#3B82F6',
    headerBg: '#111827',
    headerText: '#F9FAFB',
    sidebarBg: '#FFFFFF',
    sidebarText: '#374151',
    sidebarAccent: '#3B82F6',
    bodyText: '#374151',
    bodySecondary: '#6B7280',
    sectionTitle: '#111827',
    divider: '#3B82F6',
  },
  fonts: {
    heading: 'Courier',
    headingBold: 'Courier-Bold',
    body: 'Helvetica',
    bodyBold: 'Helvetica-Bold',
  },
  spacing: { pagePadding: 24, sectionGap: 12, itemGap: 6, sidebarWidth: '100%' },
  style: {
    headerCentered: false,
    sectionTitleUppercase: true,
    sectionTitleBorder: true,
    bulletChar: '>',
    nameSize: 22,
    titleSize: 11,
    sectionTitleSize: 10,
    bodySize: 9,
    smallSize: 8,
  },
}

export const compactConfig: TemplateConfig = {
  id: 'compact',
  name: 'Compact',
  description: 'Dense single-page, smaller fonts, efficient spacing',
  layout: 'single-column',
  premium: true,
  colors: {
    primary: '#1E40AF',
    primaryLight: '#93C5FD',
    headerBg: '#FFFFFF',
    headerText: '#1E40AF',
    sidebarBg: '#FFFFFF',
    sidebarText: '#374151',
    sidebarAccent: '#1E40AF',
    bodyText: '#374151',
    bodySecondary: '#6B7280',
    sectionTitle: '#1E40AF',
    divider: '#DBEAFE',
  },
  fonts: {
    heading: 'Helvetica',
    headingBold: 'Helvetica-Bold',
    body: 'Helvetica',
    bodyBold: 'Helvetica-Bold',
  },
  spacing: { pagePadding: 18, sectionGap: 8, itemGap: 4, sidebarWidth: '100%' },
  style: {
    headerCentered: false,
    sectionTitleUppercase: true,
    sectionTitleBorder: true,
    bulletChar: '\u2022',
    nameSize: 18,
    titleSize: 9,
    sectionTitleSize: 9,
    bodySize: 8,
    smallSize: 7,
  },
}

export const elegantConfig: TemplateConfig = {
  id: 'elegant',
  name: 'Elegant',
  description: 'Thin borders, light gray palette, refined typography',
  layout: 'single-column',
  premium: true,
  colors: {
    primary: '#6B7280',
    primaryLight: '#D1D5DB',
    headerBg: '#FFFFFF',
    headerText: '#374151',
    sidebarBg: '#FFFFFF',
    sidebarText: '#4B5563',
    sidebarAccent: '#9CA3AF',
    bodyText: '#4B5563',
    bodySecondary: '#9CA3AF',
    sectionTitle: '#374151',
    divider: '#E5E7EB',
  },
  fonts: {
    heading: 'Times-Roman',
    headingBold: 'Times-Bold',
    body: 'Helvetica',
    bodyBold: 'Helvetica-Bold',
  },
  spacing: { pagePadding: 32, sectionGap: 14, itemGap: 8, sidebarWidth: '100%' },
  style: {
    headerCentered: true,
    sectionTitleUppercase: false,
    sectionTitleBorder: true,
    bulletChar: '\u2013',
    nameSize: 22,
    titleSize: 11,
    sectionTitleSize: 11,
    bodySize: 9,
    smallSize: 8,
  },
}

export const boldConfig: TemplateConfig = {
  id: 'bold',
  name: 'Bold',
  description: 'Large name, high-contrast black/blue, strong sections',
  layout: 'single-column',
  premium: true,
  colors: {
    primary: '#1E3A8A',
    primaryLight: '#3B82F6',
    headerBg: '#1E3A8A',
    headerText: '#FFFFFF',
    sidebarBg: '#FFFFFF',
    sidebarText: '#111827',
    sidebarAccent: '#1E3A8A',
    bodyText: '#111827',
    bodySecondary: '#4B5563',
    sectionTitle: '#1E3A8A',
    divider: '#1E3A8A',
  },
  fonts: {
    heading: 'Helvetica',
    headingBold: 'Helvetica-Bold',
    body: 'Helvetica',
    bodyBold: 'Helvetica-Bold',
  },
  spacing: { pagePadding: 24, sectionGap: 14, itemGap: 8, sidebarWidth: '100%' },
  style: {
    headerCentered: false,
    sectionTitleUppercase: true,
    sectionTitleBorder: true,
    bulletChar: '\u25CF',
    nameSize: 28,
    titleSize: 13,
    sectionTitleSize: 12,
    bodySize: 10,
    smallSize: 8,
  },
}

export const corporateConfig: TemplateConfig = {
  id: 'corporate',
  name: 'Corporate',
  description: 'Conservative gray, traditional serif, formal layout',
  layout: 'single-column',
  premium: true,
  colors: {
    primary: '#4B5563',
    primaryLight: '#9CA3AF',
    headerBg: '#FFFFFF',
    headerText: '#1F2937',
    sidebarBg: '#FFFFFF',
    sidebarText: '#374151',
    sidebarAccent: '#4B5563',
    bodyText: '#374151',
    bodySecondary: '#6B7280',
    sectionTitle: '#1F2937',
    divider: '#D1D5DB',
  },
  fonts: {
    heading: 'Times-Roman',
    headingBold: 'Times-Bold',
    body: 'Times-Roman',
    bodyBold: 'Times-Bold',
  },
  spacing: { pagePadding: 30, sectionGap: 14, itemGap: 8, sidebarWidth: '100%' },
  style: {
    headerCentered: true,
    sectionTitleUppercase: true,
    sectionTitleBorder: true,
    bulletChar: '\u2022',
    nameSize: 22,
    titleSize: 11,
    sectionTitleSize: 11,
    bodySize: 10,
    smallSize: 8,
  },
}

export const startupConfig: TemplateConfig = {
  id: 'startup',
  name: 'Startup',
  description: 'Green accents, modern sans-serif, casual professional',
  layout: 'two-column-left',
  premium: true,
  colors: {
    primary: '#059669',
    primaryLight: '#6EE7B7',
    headerBg: '#FFFFFF',
    headerText: '#059669',
    sidebarBg: '#F0FDF4',
    sidebarText: '#1F2937',
    sidebarAccent: '#059669',
    bodyText: '#1F2937',
    bodySecondary: '#6B7280',
    sectionTitle: '#059669',
    divider: '#6EE7B7',
  },
  fonts: {
    heading: 'Helvetica',
    headingBold: 'Helvetica-Bold',
    body: 'Helvetica',
    bodyBold: 'Helvetica-Bold',
  },
  spacing: { pagePadding: 24, sectionGap: 14, itemGap: 8, sidebarWidth: '33%' },
  style: {
    headerCentered: false,
    sectionTitleUppercase: false,
    sectionTitleBorder: false,
    bulletChar: '\u2022',
    nameSize: 22,
    titleSize: 11,
    sectionTitleSize: 11,
    bodySize: 9,
    smallSize: 8,
  },
}

export const academicConfig: TemplateConfig = {
  id: 'academic',
  name: 'Academic',
  description: 'Research-focused, institutional feel',
  layout: 'single-column',
  premium: true,
  colors: {
    primary: '#7C2D12',
    primaryLight: '#FB923C',
    headerBg: '#FFFFFF',
    headerText: '#7C2D12',
    sidebarBg: '#FFFFFF',
    sidebarText: '#374151',
    sidebarAccent: '#7C2D12',
    bodyText: '#374151',
    bodySecondary: '#6B7280',
    sectionTitle: '#7C2D12',
    divider: '#FED7AA',
  },
  fonts: {
    heading: 'Times-Roman',
    headingBold: 'Times-Bold',
    body: 'Times-Roman',
    bodyBold: 'Times-Bold',
  },
  spacing: { pagePadding: 30, sectionGap: 14, itemGap: 8, sidebarWidth: '100%' },
  style: {
    headerCentered: true,
    sectionTitleUppercase: false,
    sectionTitleBorder: true,
    bulletChar: '\u2022',
    nameSize: 22,
    titleSize: 11,
    sectionTitleSize: 11,
    bodySize: 10,
    smallSize: 8,
  },
}

export const designerConfig: TemplateConfig = {
  id: 'designer',
  name: 'Designer',
  description: 'Asymmetric layout, accent sidebar, creative spacing',
  layout: 'two-column-left',
  premium: true,
  colors: {
    primary: '#7C3AED',
    primaryLight: '#C4B5FD',
    headerBg: '#7C3AED',
    headerText: '#FFFFFF',
    sidebarBg: '#7C3AED',
    sidebarText: '#FFFFFF',
    sidebarAccent: '#FDE68A',
    bodyText: '#1F2937',
    bodySecondary: '#6B7280',
    sectionTitle: '#7C3AED',
    divider: '#C4B5FD',
  },
  fonts: {
    heading: 'Helvetica',
    headingBold: 'Helvetica-Bold',
    body: 'Helvetica',
    bodyBold: 'Helvetica-Bold',
  },
  spacing: { pagePadding: 0, sectionGap: 14, itemGap: 8, sidebarWidth: '35%' },
  style: {
    headerCentered: false,
    sectionTitleUppercase: false,
    sectionTitleBorder: false,
    bulletChar: '\u25B8',
    nameSize: 24,
    titleSize: 11,
    sectionTitleSize: 11,
    bodySize: 9,
    smallSize: 8,
  },
}

export const PREMIUM_CONFIGS: TemplateConfig[] = [
  executiveConfig,
  creativeConfig,
  techConfig,
  compactConfig,
  elegantConfig,
  boldConfig,
  corporateConfig,
  startupConfig,
  academicConfig,
  designerConfig,
]
